baseURL = "https://my-blog-ten-sigma-14.vercel.app/"
languageCode = "zh-cn"
title = "Sky-given 的技术博客"
theme = "hugo-theme-stack"

# 强制使用 v3 版本，彻底解决 v4 兼容性报错
[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[params]
    header = {
        title = "Sky-given",
        subtitle = "探索 Hugo 的第 1 天"
    }
    footer = {
        since = 2026
    }
